#define NUM_INPUTS                      1
#define LENGTH                          2
#define LABEL                           3
#define COLON                           4
#define MUL                             5
#define LPAREN                          6
#define RPAREN                          7
#define ADD                             8
#define MULCONST                        9
#define LBRACKET                       10
#define RBRACKET                       11
#define ADDCONST                       12
#define WIRE                           13
#define NUM                            14
